version: '3'
services:
  kie_server_base:
    image: jboss/kie-server:latest
    build:
      context: ./kie-server/base

  drools_wb_base:
    image: jboss/drools-workbench:latest
    build:
      context: ./drools-wb/base

  jbpm_wb_base:
      image: jboss/jbpm-workbench:latest
      build:
        # assume checked out with the same parent directory
        context: ../jbpm/base
