version: '3'
services:
  kie_server:
    image: jboss/kie-server-showcase:latest
    build: 
      context: "./kie-server/showcase"
    ports:
     - "8081:8080"
    links:
     - kie_wb
    volumes:
     - "m2-data:/opt/jboss/.m2/repository"
    environment:
     - KIE_SERVER_LOCATION=http://kie_server:8080/kie-server/services/rest/server 
     - KIE_SERVER_CONTROLLER http://kie_wb:8080/drools-wb/rest/controller

  kie_wb:
    #image: jboss/drools-workbench-showcase:latest
    #build:
    #  context: "./drools-wb/showcase"
    image: jboss/jbpm-workbench-showcase:latest
    ports:
    - "8080:8080"
    - "8001:8001"
    - "9990:9990"
    volumes:
     - "m2-data:/opt/jboss/.m2/repository"
    environment:
    - JAVA_OPTS=-Djava.net.preferIPv4Stack=true

volumes:
  m2-data: